name: base
channels:
  - defaults
  - anaconda
  - bioconda
  - conda-forge
dependencies:
  - jupyterlab
  - matplotlib
  - mlflow
  - mmseqs2
  - numpy
  - pandas
  - pytorch
  - scikit-bio
  - scikit-learn
